---
title:               Josh Kerr
tagline:             Startups + Mobility + Geekery
login:               <%= ENV["obtvse_login"] ? ENV["obtvse_login"] : "joshkerr" %>
password:            <%= ENV["obtvse_password"] ? ENV["obtvse_password"] : "rrek1209" %>
name:                Josh Kerr
twitter:             joshkerr
github:              joshkerr
email:               joshkerr@gmail.com
google_analytics_id: UA-9009358-1